#Low Power States低功耗配置
CONFIG_ZMK_IDLE_TIMEOUT=120000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
#nkro全键无冲
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
#ws2812轴灯
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
#indicator
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

#zmk studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=1800
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=10
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=30
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=64
CONFIG_ZMK_USB_BOOT=y
CONFIG_ZMK_USB_INIT_PRIORITY=50
CONFIG_USB_HID_POLL_INTERVAL_MS=1
CONFIG_ZMK_BLE=y

#ssd1306 oled屏幕
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT=y
CONFIG_INPUT_AZOTEQ_IQS5XX=y