#Low Power States低功耗配置
CONFIG_ZMK_IDLE_TIMEOUT=120000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
#nkro全键无冲
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
#ws2812轴灯
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

#zmk studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=1800
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=10
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=30
CONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=64
CONFIG_ZMK_USB_BOOT=y
CONFIG_ZMK_USB_INIT_PRIORITY=50
CONFIG_USB_HID_POLL_INTERVAL_MS=1
CONFIG_ZMK_BLE=y
#encoder编码器
#trackball轨迹球
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_INVERT_Y=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
CONFIG_PMW3610_LOG_LEVEL_DBG=y
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=300 
#ssd1306 oled屏幕






#  west build -d build -S studio-rpc-usb-uart -b nrfmicro_13 -- -DSHIELD=numpad
#  west build -p -b nrfmicro_13 -- -DSHIELD=numpad
#  west build -p -b nrfmicro_13 -- -DSHIELD=numpad -DZMK_EXTRA_MODULES="C:\Users\13502\Downloads\zmk-pmw3610-driver"
#  west build -p -b nrfmicro_13 -- -DSHIELD=numpad -DZMK_EXTRA_MODULES="C:\Users\13502\zmk\app\module\drivers\zmk-nice-oled;C:\Users\13502\zmk\app\module\drivers\zmk-pmw3610-driver"
